import {describe, expect, it} from "vitest";

import {
  base64ToBytes,
  buildPortraitPrompt,
  detectImageFormat,
  validateCanonicalizeInput,
  validateGenerationInput,
} from "../../worker/index";

const validInput = {
  planetId: "ets2-1",
  nodeId: "ets2-1-s1-n0",
  nodeKind: "founder",
  speciesOwner: "0x1111111111111111111111111111111111111111",
  speciesName: "Cindermite",
  bodyPlan: "quadruped",
  founderDescription: "A low four-legged grazer with dark heat-sensitive skin.",
  phenotypeSummary: "A low four-legged grazer with dark heat-sensitive skin.",
  visualTraits: ["recognizable quadruped body plan", "dark heat-sensitive skin"],
  ancestorUrls: [],
};

describe("v2 portrait service input boundary", () => {
  it("accepts founder, one-parent, and two-parent ancestry", () => {
    const founder = validateGenerationInput(validInput);
    expect(buildPortraitPrompt(founder)).toContain("founder portrait");
    expect(founder.reuseExisting).toBe(true);

    const adapted = validateGenerationInput({
      ...validInput,
      nodeId: "ets2-1-n1",
      nodeKind: "adapt",
      ancestorUrls: ["https://worker.example/api/portraits/11111111-1111-4111-8111-111111111111"],
    });
    expect(buildPortraitPrompt(adapted)).toContain("input image 0");

    const hybrid = validateGenerationInput({
      ...validInput,
      nodeId: "ets2-1-n2",
      nodeKind: "merge",
      ancestorUrls: [
        "https://worker.example/api/portraits/11111111-1111-4111-8111-111111111111",
        "https://worker.example/api/portraits/22222222-2222-4222-8222-222222222222",
      ],
    });
    expect(buildPortraitPrompt(hybrid)).toContain("two exact DNA parents");
    expect(validateGenerationInput({...validInput, reuseExisting: false}).reuseExisting).toBe(false);
  });

  it("allows fictional humanoids without losing the requested anatomy", () => {
    const humanoid = validateGenerationInput({
      ...validInput,
      speciesName: "Humunus",
      bodyPlan: "bilateral",
      founderDescription: "Human shaped creatures with spikes on their back and a horn on their forehead.",
      phenotypeSummary: "Human shaped creatures with spikes on their back and a horn on their forehead.",
      visualTraits: [
        "recognizable bilateral body plan",
        "back spikes and one forehead horn",
      ],
    });
    const prompt = buildPortraitPrompt(humanoid);

    expect(prompt).toContain("Human-shaped, humanoid, or bipedal biology is allowed");
    expect(prompt).toContain("upright torso, two legs, and two grasping arms");
    expect(prompt).toContain("do not turn it into a quadruped");
    expect(prompt).toContain("species-name lettering");
    expect(prompt).not.toContain("No humans");
  });

  it("rejects invalid IDs, owners, traits, and ancestry counts", () => {
    expect(() => validateGenerationInput({...validInput, speciesOwner: "alice"})).toThrow("species_owner_length_invalid");
    expect(() => validateGenerationInput({...validInput, nodeId: "../secret"})).toThrow("invalid_chain_identifier");
    expect(() => validateGenerationInput({...validInput, visualTraits: []})).toThrow("visual_traits_invalid");
    expect(() => validateGenerationInput({...validInput, nodeKind: "merge"})).toThrow("ancestor_count_invalid");
    expect(() => validateGenerationInput({...validInput, nodeKind: "adapt", ancestorUrls: []})).toThrow("ancestor_count_invalid");
  });

  it("decodes generated bytes and detects their image type", () => {
    expect(Array.from(base64ToBytes("AQIDBA=="))).toEqual([1, 2, 3, 4]);
    expect(detectImageFormat(new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0, 0, 0, 0]))).toEqual({
      mimeType: "image/png",
      extension: "png",
    });
    expect(detectImageFormat(new Uint8Array([0xff, 0xd8, 0xff]))).toEqual({
      mimeType: "image/jpeg",
      extension: "jpg",
    });
  });

  it("requires the exact node identifier before retaining a portrait", () => {
    expect(validateCanonicalizeInput({
      speciesOwner: validInput.speciesOwner,
      nodeId: validInput.nodeId,
      sha256: `sha256:${"ab".repeat(32)}`,
    }).nodeId).toBe(validInput.nodeId);
    expect(() => validateCanonicalizeInput({
      speciesOwner: validInput.speciesOwner,
      nodeId: validInput.nodeId,
      sha256: "sha256:nope",
    })).toThrow("sha256_length_invalid");
  });
});
